insert into public.courses (
  slug,
  code,
  title,
  category,
  label,
  price_aud,
  duration,
  description,
  overview,
  image_url,
  external_video_url,
  delivery_modes,
  entry_requirements,
  career_outcomes,
  unit_summary,
  availability,
  price_label,
  duration_details,
  fee_details,
  delivery_strategy,
  source_archive_url,
  is_active
)
values (
  'ai-productivity-masterclass',
  'AI-PROD-100',
  'AI Productivity Masterclass',
  'Business',
  'New masterclass',
  100,
  '8 modules + bonus module',
  'A practical, hands-on masterclass for using AI to write faster, make decisions faster, and reclaim hours every week—without coding.',
  'Learn how to use accessible AI tools for email, documents, meetings, marketing, planning, customer service, and video creation. The course is designed for beginners and focuses on real tasks, ready-to-use prompts, and repeatable workflows.',
  '/images/courses/ai-productivity-masterclass.png',
  '',
  '["Online", "Self paced", "Practical activities"]'::jsonb,
  '["No coding or technical experience required", "Access to a web browser and an email address", "A free AI assistant account is sufficient for the activities"]'::jsonb,
  '["Faster professional writing and communication", "Practical AI-assisted business workflows", "More efficient meetings, research, and content creation"]'::jsonb,
  '8 practical modules plus a bonus workflow library.',
  'open',
  '$100',
  'Work through eight example-driven modules and a bonus library of real-world workflows at your own pace.',
  'One-time course fee of AUD $100.',
  'Plain-English demonstrations, guided practice, a structured handbook, and ready-to-use prompts built around everyday work.',
  '/course-materials/ai-productivity-handbook.docx',
  true
)
on conflict (slug) do update set
  code = excluded.code,
  title = excluded.title,
  category = excluded.category,
  label = excluded.label,
  price_aud = excluded.price_aud,
  duration = excluded.duration,
  description = excluded.description,
  overview = excluded.overview,
  image_url = excluded.image_url,
  external_video_url = excluded.external_video_url,
  delivery_modes = excluded.delivery_modes,
  entry_requirements = excluded.entry_requirements,
  career_outcomes = excluded.career_outcomes,
  unit_summary = excluded.unit_summary,
  availability = excluded.availability,
  price_label = excluded.price_label,
  duration_details = excluded.duration_details,
  fee_details = excluded.fee_details,
  delivery_strategy = excluded.delivery_strategy,
  source_archive_url = excluded.source_archive_url,
  is_active = excluded.is_active,
  updated_at = now();

insert into public.course_units (course_slug, code, title, type, position)
values
  ('ai-productivity-masterclass', 'M01', 'Why AI Matters to You', 'Skill set', 1),
  ('ai-productivity-masterclass', 'M02', 'Mastering the Art of the Prompt', 'Skill set', 2),
  ('ai-productivity-masterclass', 'M03', 'Your AI Productivity Toolbox', 'Skill set', 3),
  ('ai-productivity-masterclass', 'M04', 'Master Email, Documents & PDF Productivity', 'Skill set', 4),
  ('ai-productivity-masterclass', 'M05', 'Meetings, Transcripts & Presentations', 'Skill set', 5),
  ('ai-productivity-masterclass', 'M06', 'AI for Small Business', 'Skill set', 6),
  ('ai-productivity-masterclass', 'M07', 'AI for Everyday Life', 'Skill set', 7),
  ('ai-productivity-masterclass', 'M08', 'Create Your First AI Video', 'Skill set', 8),
  ('ai-productivity-masterclass', 'BONUS', 'Real-Life AI Workflows', 'Skill set', 9)
on conflict (course_slug, code) do update set
  title = excluded.title,
  type = excluded.type,
  position = excluded.position,
  updated_at = now();
